apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: application/pour-tilt
        ports:
        - containerPort: 80